package persistence

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	auditdomain "github.com/byteBuilderX/stratum/internal/audit/domain"
	"github.com/byteBuilderX/stratum/internal/knowledge/domain"
)

// WorkspaceRepo persists knowledge workspaces in per-tenant schemas.
type WorkspaceRepo struct {
	db poolIface
}

// NewWorkspaceRepo constructs a WorkspaceRepo backed by the given pool.
func NewWorkspaceRepo(db poolIface) *WorkspaceRepo {
	return &WorkspaceRepo{db: db}
}

// jsonbConfig matches the JSONB shape stored in rag_workspaces.config.
type jsonbConfig struct {
	EmbeddingModel   string  `json:"embedding_model"`
	ChunkSize        int     `json:"chunk_size"`
	ChunkOverlap     int     `json:"chunk_overlap"`
	QueryMode        string  `json:"query_mode"`
	TopK             int     `json:"top_k"`
	ChunkingStrategy string  `json:"chunking_strategy"`
	Reranking        string  `json:"reranking,omitempty"`
	ScoreThreshold   float32 `json:"score_threshold,omitempty"`
	RerankTopK       int     `json:"rerank_top_k,omitempty"`
}

func toJSONB(c domain.WorkspaceConfig) string {
	b, _ := json.Marshal(jsonbConfig{
		EmbeddingModel:   c.EmbeddingModel,
		ChunkSize:        c.ChunkSize,
		ChunkOverlap:     c.ChunkOverlap,
		QueryMode:        c.QueryMode,
		TopK:             c.TopK,
		ChunkingStrategy: c.ChunkingStrategy,
		Reranking:        c.Reranking,
		ScoreThreshold:   c.ScoreThreshold,
		RerankTopK:       c.RerankTopK,
	})
	return string(b)
}

func fromJSONB(c jsonbConfig) domain.WorkspaceConfig {
	return domain.WorkspaceConfig{
		EmbeddingModel:   c.EmbeddingModel,
		ChunkSize:        c.ChunkSize,
		ChunkOverlap:     c.ChunkOverlap,
		QueryMode:        c.QueryMode,
		TopK:             c.TopK,
		ChunkingStrategy: c.ChunkingStrategy,
		Reranking:        c.Reranking,
		ScoreThreshold:   c.ScoreThreshold,
		RerankTopK:       c.RerankTopK,
	}
}

// insertChangeAudit inserts the audit row in the SAME transaction as the
// business write; an audit failure rolls the business change back (fail
// closed). A nil event skips auditing — reserved for internal reentrant
// paths. Incomplete events are a caller bug and fail the transaction.
// tenantID is explicit because knowledge repos receive it as a parameter
// rather than from the tenant context.
func insertChangeAudit(ctx context.Context, tx pgx.Tx, tenantID string, ev *auditdomain.ResourceChangeAuditEvent) error {
	ev = ev.Normalized()
	if ev == nil {
		return nil
	}
	if ev.ResourceID == "" || ev.Operation == "" || ev.ResourceKind == "" {
		return fmt.Errorf("change audit: incomplete event (kind=%s id=%q op=%q)",
			ev.ResourceKind, ev.ResourceID, ev.Operation)
	}
	_, err := tx.Exec(ctx, auditdomain.ChangeAuditInsertSQL,
		uuid.Must(uuid.NewV7()).String(), tenantID,
		ev.ResourceKind, ev.ResourceID, ev.Operation, ev.ActorID, ev.ActorType, ev.Source,
		ev.ProposalID, ev.Before, ev.After)
	if err != nil {
		return fmt.Errorf("insert change audit %s %s: %w", ev.ResourceKind, ev.ResourceID, err)
	}
	return nil
}

// Create inserts a workspace, returning ErrWorkspaceConflict on unique violation.
func (r *WorkspaceRepo) Create(ctx context.Context, tenantID string, ws *domain.Workspace, audit *auditdomain.ResourceChangeAuditEvent) error {
	var id string
	err := execTenant(ctx, r.db, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		if err := tx.QueryRow(ctx, `INSERT INTO rag_workspaces (name, description, config, created_by)
	                     VALUES ($1, $2, $3, $4) RETURNING id`,
			ws.Name, ws.Description, toJSONB(ws.Config), ws.CreatedBy,
		).Scan(&id); err != nil {
			return err
		}
		// The workspace ID is generated by the database, so the audit row must
		// reference it after the INSERT returns it.
		if audit != nil {
			audit.ResourceID = id
		}
		return insertChangeAudit(ctx, tx, tenantID, audit)
	})
	if err != nil {
		if strings.Contains(err.Error(), "unique") || strings.Contains(err.Error(), "duplicate") {
			return domain.ErrWorkspaceConflict
		}
		return fmt.Errorf("workspace_repo: create: %w", err)
	}
	ws.ID = id
	return nil
}

// GetByName returns a workspace by name; ErrWorkspaceNotFound if absent.
func (r *WorkspaceRepo) GetByName(ctx context.Context, tenantID, name string) (*domain.Workspace, error) {
	var (
		ws domain.Workspace
		jc jsonbConfig
	)
	err := execTenant(ctx, r.db, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		return tx.QueryRow(ctx, `SELECT id, name, COALESCE(description,''), config,
		                     COALESCE(system_key,''), COALESCE(management_mode,'tenant_managed'),
		                     COALESCE(created_by,''), created_at, updated_at
	                     FROM rag_workspaces WHERE name = $1`, name,
		).Scan(&ws.ID, &ws.Name, &ws.Description, &jc,
			&ws.SystemKey, &ws.ManagementMode,
			&ws.CreatedBy, &ws.CreatedAt, &ws.UpdatedAt)
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrWorkspaceNotFound
		}
		return nil, fmt.Errorf("workspace_repo: get by name: %w", err)
	}
	ws.Config = fromJSONB(jc)
	return &ws, nil
}

// GetByID returns a workspace by UUID; ErrWorkspaceNotFound if absent.
func (r *WorkspaceRepo) GetByID(ctx context.Context, tenantID, id string) (*domain.Workspace, error) {
	var (
		ws domain.Workspace
		jc jsonbConfig
	)
	err := execTenant(ctx, r.db, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		return tx.QueryRow(ctx, `SELECT id, name, COALESCE(description,''), config,
		                     COALESCE(system_key,''), COALESCE(management_mode,'tenant_managed'),
		                     COALESCE(created_by,''), created_at, updated_at
	                     FROM rag_workspaces WHERE id = $1::uuid`, id,
		).Scan(&ws.ID, &ws.Name, &ws.Description, &jc,
			&ws.SystemKey, &ws.ManagementMode,
			&ws.CreatedBy, &ws.CreatedAt, &ws.UpdatedAt)
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrWorkspaceNotFound
		}
		return nil, fmt.Errorf("workspace_repo: get by id: %w", err)
	}
	ws.Config = fromJSONB(jc)
	return &ws, nil
}

// List returns workspaces ordered by created_at DESC.
func (r *WorkspaceRepo) List(ctx context.Context, tenantID string) ([]*domain.Workspace, error) {
	var out []*domain.Workspace
	err := execTenant(ctx, r.db, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `SELECT id, name, COALESCE(description,''), config,
		                     COALESCE(system_key,''), COALESCE(management_mode,'tenant_managed'),
		                     COALESCE(created_by,''), created_at, updated_at
	                     FROM rag_workspaces ORDER BY created_at DESC`)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			var ws domain.Workspace
			var jc jsonbConfig
			if err := rows.Scan(&ws.ID, &ws.Name, &ws.Description, &jc,
				&ws.SystemKey, &ws.ManagementMode,
				&ws.CreatedBy, &ws.CreatedAt, &ws.UpdatedAt); err != nil {
				return fmt.Errorf("workspace_repo: scan list row: %w", err)
			}
			ws.Config = fromJSONB(jc)
			out = append(out, &ws)
		}
		return rows.Err()
	})
	if err != nil {
		return nil, fmt.Errorf("workspace_repo: list: %w", err)
	}
	return out, nil
}

// UpdateWorkspaceAll applies rename, description and config atomically in one
// transaction, then writes the change audit in the same transaction. renameTo
// and description may be nil to leave the column untouched; the config is
// always written (callers pass the merged value). ErrWorkspaceNotFound on 0
// rows, ErrWorkspaceConflict on duplicate rename.
func (r *WorkspaceRepo) UpdateWorkspaceAll(
	ctx context.Context, tenantID, name string,
	renameTo, description *string,
	cfg domain.WorkspaceConfig,
	audit *auditdomain.ResourceChangeAuditEvent,
) error {
	var tag pgconn.CommandTag
	err := execTenant(ctx, r.db, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		var err error
		tag, err = tx.Exec(ctx, `UPDATE rag_workspaces
	                     SET name = COALESCE($1, name),
	                         description = COALESCE($2, description),
	                         config = $3,
	                         updated_at = NOW()
			WHERE name = $4`, renameTo, description, toJSONB(cfg), name)
		if err != nil {
			return err
		}
		return insertChangeAudit(ctx, tx, tenantID, audit)
	})
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return domain.ErrWorkspaceConflict
		}
		return fmt.Errorf("workspace_repo: update: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return domain.ErrWorkspaceNotFound
	}
	return nil
}

func (r *WorkspaceRepo) Delete(ctx context.Context, tenantID, name string, audit *auditdomain.ResourceChangeAuditEvent) error {
	var tag pgconn.CommandTag
	err := execTenant(ctx, r.db, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		var err error
		tag, err = tx.Exec(ctx, `DELETE FROM rag_workspaces WHERE name = $1`, name)
		if err != nil {
			return err
		}
		return insertChangeAudit(ctx, tx, tenantID, audit)
	})
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23503" {
			return domain.ErrWorkspaceLinked
		}
		return fmt.Errorf("workspace_repo: delete: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return domain.ErrWorkspaceNotFound
	}
	return nil
}

// GetConfigForUpload returns just the config of a workspace; ErrWorkspaceNotFound if absent.
func (r *WorkspaceRepo) GetConfigForUpload(ctx context.Context, tenantID, name string) (domain.WorkspaceConfig, error) {
	var jc jsonbConfig
	err := execTenant(ctx, r.db, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		return tx.QueryRow(ctx, `SELECT config FROM rag_workspaces WHERE name = $1`, name).Scan(&jc)
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.WorkspaceConfig{}, domain.ErrWorkspaceNotFound
		}
		return domain.WorkspaceConfig{}, fmt.Errorf("workspace_repo: get config: %w", err)
	}
	return fromJSONB(jc), nil
}

// GetConfigByID returns just the config of a workspace resolved by UUID; ErrWorkspaceNotFound if absent.
func (r *WorkspaceRepo) GetConfigByID(ctx context.Context, tenantID, id string) (domain.WorkspaceConfig, error) {
	var jc jsonbConfig
	err := execTenant(ctx, r.db, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		return tx.QueryRow(ctx, `SELECT config FROM rag_workspaces WHERE id = $1::uuid`, id).Scan(&jc)
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.WorkspaceConfig{}, domain.ErrWorkspaceNotFound
		}
		return domain.WorkspaceConfig{}, fmt.Errorf("workspace_repo: get config by id: %w", err)
	}
	return fromJSONB(jc), nil
}
