package persistence

import (
	"context"
	"encoding/json"
	"errors"
	"testing"

	"github.com/pashagolub/pgxmock/v2"
	"github.com/stretchr/testify/require"

	auditdomain "github.com/byteBuilderX/stratum/internal/audit/domain"
	"github.com/byteBuilderX/stratum/internal/knowledge/domain"
	pkgversioning "github.com/byteBuilderX/stratum/pkg/versioning"
)

// TestWorkspaceRepoUpdateWritesPublishedVersion locks the full UpdateWorkspaceAll
// transaction: resolve id → UPDATE → Demote→Insert→SetActive version write →
// audit INSERT → Commit. The new version id is generated by the repo, so the
// INSERT/SETACTIVE args that carry it use AnyArg.
func TestWorkspaceRepoUpdateWritesPublishedVersion(t *testing.T) {
	mock := newRepoMock(t)
	repo := NewWorkspaceRepo(mock)

	snap := domain.SnapshotFromWorkspace(&domain.Workspace{Name: "kb", Description: "d", Config: domain.WorkspaceConfig{TopK: 8}})

	repoBeginTenant(mock)
	mock.ExpectQuery("SELECT id FROM rag_workspaces WHERE name=\\$1").
		WithArgs("kb").
		WillReturnRows(pgxmock.NewRows([]string{"id"}).AddRow("ws-1"))
	mock.ExpectExec("UPDATE rag_workspaces").
		WithArgs((*string)(nil), (*string)(nil), pgxmock.AnyArg(), "kb").
		WillReturnResult(pgxmock.NewResult("UPDATE", 1))
	expectKnowledgeVersionWrite(mock, "ws-1", "u1")
	mock.ExpectExec("INSERT INTO resource_change_audits").
		WithArgs(
			pgxmock.AnyArg(),      // id（uuid）
			"tenant-1",            // tenant_id
			"knowledge",           // resource_kind
			"ws-1",                // resource_id
			"update",              // operation
			"",                    // actor_id
			"user",                // actor_type（Normalized 默认）
			"api",                 // source（Normalized 默认）
			"",                    // proposal_id
			json.RawMessage("{}"), // before_projection
			json.RawMessage("{}"), // after_projection
		).
		WillReturnResult(pgxmock.NewResult("INSERT", 1))
	mock.ExpectCommit()

	audit := &auditdomain.ResourceChangeAuditEvent{ResourceKind: "knowledge", ResourceID: "ws-1", Operation: "update"}
	err := repo.UpdateWorkspaceAll(context.Background(), "tenant-1", "kb", nil, nil, snap, "", "u1", audit)
	require.NoError(t, err)
	require.NoError(t, mock.ExpectationsWereMet())
}

// TestWorkspaceRepoRollback_SuccessRepointsActive locks the RollbackWorkspace
// success path: resolve id → UPDATE row from snapshot → RollbackVersionTx
// (Demote current + promote target) → SetActive repoint → Commit.
func TestWorkspaceRepoRollback_SuccessRepointsActive(t *testing.T) {
	mock := newRepoMock(t)
	repo := NewWorkspaceRepo(mock)

	snap := domain.SnapshotFromWorkspace(&domain.Workspace{Name: "old", Description: "od", Config: domain.WorkspaceConfig{TopK: 4}})

	repoBeginTenant(mock)
	mock.ExpectQuery("SELECT id FROM rag_workspaces WHERE name=\\$1").
		WithArgs("kb").
		WillReturnRows(pgxmock.NewRows([]string{"id"}).AddRow("ws-1"))
	mock.ExpectExec("UPDATE rag_workspaces").
		WithArgs("old", "od", pgxmock.AnyArg(), "ws-1").
		WillReturnResult(pgxmock.NewResult("UPDATE", 1))
	mock.ExpectExec("UPDATE resource_versions SET status='deprecated'").
		WithArgs("knowledge", "ws-1").WillReturnResult(pgxmock.NewResult("UPDATE", 1))
	mock.ExpectExec("UPDATE resource_versions SET status='published'").
		WithArgs("knowledge", "ws-1", "v2").WillReturnResult(pgxmock.NewResult("UPDATE", 1))
	mock.ExpectExec("UPDATE rag_workspaces SET active_version_id").
		WithArgs("ws-1", "v2").WillReturnResult(pgxmock.NewResult("UPDATE", 1))
	mock.ExpectCommit()

	err := repo.RollbackWorkspace(context.Background(), "tenant-1", "kb", snap, "", "v2", nil)
	require.NoError(t, err)
	require.NoError(t, mock.ExpectationsWereMet())
}

// TestWorkspaceRepoRollback_MissingTargetFailsClosed locks the fail-closed path
// when the rollback target version does not exist: RollbackVersionTx promotes 0
// rows (RowsAffected != 1) and the whole transaction rolls back with
// versioning.ErrVersionNotFound.
func TestWorkspaceRepoRollback_MissingTargetFailsClosed(t *testing.T) {
	mock := newRepoMock(t)
	repo := NewWorkspaceRepo(mock)

	snap := domain.SnapshotFromWorkspace(&domain.Workspace{Name: "old", Description: "od", Config: domain.WorkspaceConfig{TopK: 4}})

	repoBeginTenant(mock)
	mock.ExpectQuery("SELECT id FROM rag_workspaces WHERE name=\\$1").
		WithArgs("kb").
		WillReturnRows(pgxmock.NewRows([]string{"id"}).AddRow("ws-1"))
	mock.ExpectExec("UPDATE rag_workspaces").
		WithArgs("old", "od", pgxmock.AnyArg(), "ws-1").
		WillReturnResult(pgxmock.NewResult("UPDATE", 1))
	mock.ExpectExec("UPDATE resource_versions SET status='deprecated'").
		WithArgs("knowledge", "ws-1").WillReturnResult(pgxmock.NewResult("UPDATE", 1))
	mock.ExpectExec("UPDATE resource_versions SET status='published'").
		WithArgs("knowledge", "ws-1", "v9").WillReturnResult(pgxmock.NewResult("UPDATE", 0))
	mock.ExpectRollback()

	err := repo.RollbackWorkspace(context.Background(), "tenant-1", "kb", snap, "", "v9", nil)
	require.Error(t, err)
	require.True(t, errors.Is(err, pkgversioning.ErrVersionNotFound))
	require.NoError(t, mock.ExpectationsWereMet())
}
