{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stratum.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stratum.labels" . | nindent 4 }}
    component: frontend
spec:
  selector:
    {{- include "stratum.selectorLabels" . | nindent 4 }}
    component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  type: {{ .Values.frontend.service.type }}
{{- end }}
