apiVersion: v1
kind: Service
metadata:
  name: {{ include "stratum.fullname" . }}
  labels:
    {{- include "stratum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stratum.selectorLabels" . | nindent 4 }}
