// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: admin/admin.proto

package gen

import (
	"time"
)

type CreateTenantRequest struct {
	Name   string `json:"name" binding:"required"`
	Slug   string `json:"slug" binding:"required"`
	Plan   string `json:"plan" binding:"required,oneof=free pro enterprise"`
	Status string `json:"status" binding:"required,oneof=active suspended"`
}

type UpdateTenantRequest struct {
	Plan   string `json:"plan" binding:"omitempty,oneof=free pro enterprise"`
	Status string `json:"status" binding:"omitempty,oneof=active suspended"`
}

type TenantResponse struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	Plan        string     `json:"plan"`
	Status      string     `json:"status"`
	MemberCount int32      `json:"member_count"`
	CreatedAt   time.Time  `json:"created_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
	IsDefault   bool       `json:"is_default"`
}

type ListTenantsResponse struct {
	Tenants  []TenantResponse `json:"tenants"`
	Total    int32            `json:"total"`
	Page     int32            `json:"page"`
	PageSize int32            `json:"page_size"`
}

type InviteMemberRequest struct {
	Email string `json:"email" binding:"required,email"`
	Role  string `json:"role" binding:"required,oneof=member admin"`
}

type InviteMemberResponse struct {
	InvitationCode string `json:"invitation_code"`
	Email          string `json:"email"`
	Role           string `json:"role"`
}

type UpdateMemberRoleRequest struct {
	Role string `json:"role" binding:"required,oneof=member admin"`
}

type MemberResponse struct {
	UserID      string    `json:"user_id"`
	GitHubLogin string    `json:"github_login"`
	AvatarURL   string    `json:"avatar_url"`
	Role        string    `json:"role"`
	JoinedAt    time.Time `json:"joined_at"`
}

type ListMembersResponse struct {
	Members  []MemberResponse `json:"members"`
	Total    int32            `json:"total"`
	Page     int32            `json:"page"`
	PageSize int32            `json:"page_size"`
}

type UpdateSettingsRequest struct {
	Name     string         `json:"name"`
	Settings map[string]any `json:"settings"`
}

type SettingsResponse struct {
	TenantID   string         `json:"tenant_id"`
	TenantName string         `json:"tenant_name"`
	IsDefault  bool           `json:"is_default"`
	Settings   map[string]any `json:"settings"`
}

type TenantListItem struct {
	TenantID  string `json:"tenant_id"`
	Name      string `json:"name"`
	IsDefault bool   `json:"is_default"`
}

type TenantListResponse struct {
	Tenants []TenantListItem `json:"tenants"`
}

type SearchUsersRequest struct {
	Query string `json:"query"`
	Limit int32  `json:"limit"`
}

type AdminUserResponse struct {
	UserID      string  `json:"user_id"`
	Username    string  `json:"username"`
	GitHubLogin string  `json:"github_login"`
	AvatarURL   *string `json:"avatar_url,omitempty"`
	GlobalRole  string  `json:"global_role"`
}

type SearchUsersResponse struct {
	Users []AdminUserResponse `json:"users"`
}

type ListAdminsResponse struct {
	Admins []AdminUserResponse `json:"admins"`
}

type SetAdminRoleRequest struct {
	UserID string `json:"user_id" binding:"required"`
}
