// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: agent/agent.proto

package gen

type CreateAgentRequest struct {
	Name          string   `json:"name" binding:"required,max=100"`
	Description   string   `json:"description" binding:"omitempty,max=2000"`
	SystemPrompt  string   `json:"system_prompt" binding:"omitempty,max=16384"`
	LLMModel      string   `json:"llm_model" binding:"required"`
	MaxIterations int32    `json:"max_iterations" binding:"required,min=1,max=90"`
	AllowedSkills []string `json:"allowed_skills"`
}

type AgentResponse struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Description   string   `json:"description"`
	SystemPrompt  string   `json:"system_prompt"`
	LLMModel      string   `json:"llm_model"`
	MaxIterations int32    `json:"max_iterations"`
	AllowedSkills []string `json:"allowed_skills"`
	CreatedAt     string   `json:"created_at"`
}

type ExecuteAgentRequest struct {
	Query     string         `json:"query" binding:"required"`
	Context   map[string]any `json:"context"`
	Variables map[string]any `json:"variables"`
}

type ExecuteAgentResponse struct {
	Result any         `json:"result,omitempty"`
	Steps  []AgentStep `json:"steps,omitempty"`
	Status string      `json:"status"`
	Error  string      `json:"error,omitempty"`
}

type AgentStep struct {
	Iteration int32  `json:"iteration"`
	Action    string `json:"action"`
	Tool      string `json:"tool,omitempty"`
	Input     any    `json:"input,omitempty"`
	Output    any    `json:"output,omitempty"`
}
