// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: collaboration/collaboration.proto

package gen

import (
	"github.com/byteBuilderX/stratum/internal/collab/domain"
	"time"
)

type CreateCollabRequest struct {
	TaskDescription string                `json:"task_description" binding:"required"`
	Strategy        domain.CollabStrategy `json:"strategy" binding:"required"`
	Participants    []string              `json:"participants" binding:"required"`
}

type CollabResponse struct {
	ID              string     `json:"id"`
	TaskDescription string     `json:"taskDescription"`
	Strategy        string     `json:"strategy"`
	Status          string     `json:"status"`
	CreatedBy       string     `json:"createdBy"`
	Participants    []string   `json:"participants"`
	CreatedAt       time.Time  `json:"createdAt"`
	StartedAt       *time.Time `json:"startedAt,omitempty"`
	CompletedAt     *time.Time `json:"completedAt,omitempty"`
}

type TaskStepResponse struct {
	ID           string         `json:"id"`
	PlanID       string         `json:"planId"`
	AgentID      string         `json:"agentId"`
	Dependencies []string       `json:"dependencies"`
	Status       string         `json:"status"`
	Input        map[string]any `json:"input"`
	Output       map[string]any `json:"output,omitempty"`
	Error        string         `json:"error,omitempty"`
	CreatedAt    time.Time      `json:"createdAt"`
}
