// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: dashboard/dashboard.proto

package gen

type DashboardOverviewResponse struct {
	Agents              int32 `json:"agents"`
	Skills              int32 `json:"skills"`
	KnowledgeWorkspaces int32 `json:"knowledge_workspaces"`
	MCPServers          int32 `json:"mcp_servers"`
	ModelProviders      int32 `json:"model_providers"`
	TenantMembers       int32 `json:"tenant_members"`
	Workflows           int32 `json:"workflows"`
	AgentUserMessages7d int32 `json:"agent_user_messages_7d"`
}
