// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: mcp/mcp_config.proto

package gen

import (
	"encoding/json"
	"github.com/byteBuilderX/stratum/internal/mcp/domain"
	"time"
)

type MCPServerConfigRequest struct {
	ID           string              `json:"id"`
	Name         string              `json:"name"`
	Version      string              `json:"version"`
	Transport    string              `json:"transport"`
	Command      string              `json:"command"`
	Args         []string            `json:"args"`
	URL          string              `json:"url"`
	Env          map[string]string   `json:"env"`
	Headers      map[string]string   `json:"headers,omitempty"`
	Capabilities []string            `json:"capabilities"`
	Timeout      time.Duration       `json:"timeout"`
	Auth         *domain.AuthConfig  `json:"auth,omitempty"`
	Retry        *domain.RetryConfig `json:"retry,omitempty"`
	SystemKey    json.RawMessage     `json:"system_key"`
	Editors      []string            `json:"editors"`
}

type MCPAuthConfigResponse struct {
	Type                 domain.AuthType `json:"type"`
	APIKeyHeader         string          `json:"api_key_header,omitempty"`
	OAuth2ClientID       string          `json:"oauth2_client_id,omitempty"`
	OAuth2TokenURL       string          `json:"oauth2_token_url,omitempty"`
	OAuth2Scopes         []string        `json:"oauth2_scopes,omitempty"`
	CredentialConfigured bool            `json:"credential_configured"`
}

type MCPServerConfigResponse struct {
	ID             string                 `json:"id"`
	Name           string                 `json:"name"`
	Version        string                 `json:"version"`
	Transport      string                 `json:"transport"`
	Command        string                 `json:"command"`
	Args           []string               `json:"args"`
	URL            string                 `json:"url"`
	Env            map[string]string      `json:"env"`
	Headers        map[string]string      `json:"headers,omitempty"`
	Capabilities   []string               `json:"capabilities"`
	Timeout        time.Duration          `json:"timeout"`
	Auth           *MCPAuthConfigResponse `json:"auth,omitempty"`
	Retry          *domain.RetryConfig    `json:"retry,omitempty"`
	ManagementMode string                 `json:"management_mode"`
	Editors        []string               `json:"editors"`
}
