// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: memory/memory.proto

package gen

import (
	"time"
)

type CreateMemoryRequest struct {
	Content    string  `json:"content" binding:"required"`
	Importance float64 `json:"importance"`
}

type MemoryFactResponse struct {
	ID         string    `json:"id"`
	Scope      string    `json:"scope"`
	Content    string    `json:"content"`
	Importance float64   `json:"importance"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type MemorySessionsResponse struct {
	Sessions []string `json:"sessions"`
}

type MemorySummaryResponse struct {
	Summary string `json:"summary"`
}

type MemoryStatsResponse struct {
	TotalEntries     int64     `json:"total_entries"`
	ShortTermCount   int64     `json:"short_term_count"`
	LongTermCount    int64     `json:"long_term_count"`
	EntityCount      int64     `json:"entity_count"`
	SessionsCount    int64     `json:"sessions_count"`
	ActiveUsers      int64     `json:"active_users"`
	VectorCount      int64     `json:"vector_count"`
	LastAccessTime   time.Time `json:"last_access_time"`
	StorageSizeBytes int64     `json:"storage_size_bytes"`
}
