// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: memory/memory.proto

package gen

import (
	"time"
)

type MemoryFactResponse struct {
	ID         string    `json:"id"`
	Scope      string    `json:"scope"`
	Content    string    `json:"content"`
	Importance float64   `json:"importance"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Confidence float64   `json:"confidence"`
	Category   string    `json:"category"`
	Source     string    `json:"source"`
	Status     string    `json:"status"`
}

type MemorySessionsResponse struct {
	Sessions []string `json:"sessions"`
}

type MemorySummaryResponse struct {
	Summary string `json:"summary"`
}

type MemoryStatsResponse struct {
	MemoryCount          int64 `json:"memory_count"`
	EntityCount          int64 `json:"entity_count"`
	EmbedModelConfigured bool  `json:"embed_model_configured"`
}

type MemoryEntityResponse struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	EntityType string    `json:"entity_type"`
	FactCount  int64     `json:"fact_count"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Scope      string    `json:"scope"`
}

type ListMemoryEntitiesResponse struct {
	Entities []MemoryEntityResponse `json:"entities"`
	Total    int64                  `json:"total"`
}

type MemoryMigrationResponse struct {
	ID         int64     `json:"id"`
	FromModel  string    `json:"from_model"`
	ToModel    string    `json:"to_model"`
	Status     string    `json:"status"`
	Progress   int32     `json:"progress"`
	TotalFacts int32     `json:"total_facts"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type MemoryMigrationCostResponse struct {
	FactCount        int64 `json:"fact_count"`
	EstimatedSeconds int64 `json:"estimated_seconds"`
}

type StartMemoryMigrationRequest struct {
	ToModel string `json:"to_model"`
}

type UpdateMemoryFactRequest struct {
	Content    *string  `json:"content"`
	Importance *float64 `json:"importance"`
	Category   *string  `json:"category"`
}

type ListMemoryFactsResponse struct {
	Facts []MemoryFactResponse `json:"facts"`
	Total int64                `json:"total"`
}

type MemorySummaryItemResponse struct {
	ID             string    `json:"id"`
	Summary        string    `json:"summary"`
	Tier           string    `json:"tier"`
	Importance     float64   `json:"importance"`
	ConversationID string    `json:"conversation_id"`
	PeriodEnd      time.Time `json:"period_end"`
	CreatedAt      time.Time `json:"created_at"`
	Scope          string    `json:"scope"`
}

type ListMemorySummariesResponse struct {
	Summaries []MemorySummaryItemResponse `json:"summaries"`
	Total     int64                       `json:"total"`
}

type MemorySnapshotResponse struct {
	AgentID          string    `json:"agent_id"`
	WorkContext      []string  `json:"work_context"`
	PersonalContext  []string  `json:"personal_context"`
	TopOfMind        []string  `json:"top_of_mind"`
	ExpiresAt        time.Time `json:"expires_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	Status           string    `json:"status"`
	AgentName        string    `json:"agent_name"`
	ConversationName string    `json:"conversation_name"`
}

type ListMemorySnapshotsResponse struct {
	Snapshots []MemorySnapshotResponse `json:"snapshots"`
}

type UpdateMemorySnapshotRequest struct {
	WorkContext     []string `json:"work_context"`
	PersonalContext []string `json:"personal_context"`
	TopOfMind       []string `json:"top_of_mind"`
}

type MemoryEntryItemResponse struct {
	ID         string    `json:"id"`
	Role       string    `json:"role"`
	Content    string    `json:"content"`
	Type       string    `json:"type"`
	Scope      string    `json:"scope"`
	Importance float64   `json:"importance"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiresAt  time.Time `json:"expires_at"`
}

type ListMemoryEntriesResponse struct {
	Entries []MemoryEntryItemResponse `json:"entries"`
	Total   int64                     `json:"total"`
}
