// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: memory/memory.proto

package gen

import (
	"time"
)

type MemoryFactResponse struct {
	ID         string    `json:"id"`
	Scope      string    `json:"scope"`
	Content    string    `json:"content"`
	Importance float64   `json:"importance"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type MemorySessionsResponse struct {
	Sessions []string `json:"sessions"`
}

type MemorySummaryResponse struct {
	Summary string `json:"summary"`
}

type MemoryStatsResponse struct {
	MemoryCount          int64 `json:"memory_count"`
	EntityCount          int64 `json:"entity_count"`
	EmbedModelConfigured bool  `json:"embed_model_configured"`
}

type MemoryEntityResponse struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	EntityType string    `json:"entity_type"`
	FactCount  int64     `json:"fact_count"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

type ListMemoryEntitiesResponse struct {
	Entities []MemoryEntityResponse `json:"entities"`
	Total    int64                  `json:"total"`
}

type MemoryMigrationResponse struct {
	ID         int64     `json:"id"`
	FromModel  string    `json:"from_model"`
	ToModel    string    `json:"to_model"`
	Status     string    `json:"status"`
	Progress   int32     `json:"progress"`
	TotalFacts int32     `json:"total_facts"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type MemoryMigrationCostResponse struct {
	FactCount        int64 `json:"fact_count"`
	EstimatedSeconds int64 `json:"estimated_seconds"`
}

type StartMemoryMigrationRequest struct {
	ToModel string `json:"to_model"`
}
