// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: agent/operation_proposal.proto

package gen

import (
	"encoding/json"
	"github.com/byteBuilderX/stratum/internal/agent/domain"
	"time"
)

type RejectOperationProposalRequest struct {
	Note string `json:"note" binding:"required"`
}

type OperationProposalResponse struct {
	ID                 string                  `json:"id"`
	AgentID            string                  `json:"agentId"`
	TargetAgentID      string                  `json:"targetAgentId,omitempty"`
	OpType             string                  `json:"opType"`
	Delegation         string                  `json:"delegation,omitempty"`
	MaxDailyCostUSD    float64                 `json:"maxDailyCostUsd,omitempty"`
	MaxDailyExecutions int32                   `json:"maxDailyExecutions,omitempty"`
	PayloadSummary     json.RawMessage         `json:"payloadSummary"`
	Status             domain.OpProposalStatus `json:"status"`
	ProposerID         string                  `json:"proposerId"`
	ReviewedBy         string                  `json:"reviewedBy,omitempty"`
	ReviewNote         string                  `json:"reviewNote,omitempty"`
	CreatedAt          time.Time               `json:"createdAt"`
	ResolvedAt         *time.Time              `json:"resolvedAt,omitempty"`
	ExpiresAt          *time.Time              `json:"expiresAt,omitempty"`
}
