// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: knowledge/rag.proto

package gen

import (
	"time"
)

type WorkspaceConfig struct {
	EmbeddingModel   string  `json:"embedding_model"`
	ChunkingStrategy string  `json:"chunking_strategy"`
	ChunkSize        int32   `json:"chunk_size"`
	ChunkOverlap     int32   `json:"chunk_overlap"`
	QueryMode        string  `json:"query_mode"`
	TopK             int32   `json:"top_k"`
	Reranking        string  `json:"reranking"`
	ScoreThreshold   float32 `json:"score_threshold"`
	RerankTopK       int32   `json:"rerank_top_k"`
}

type QueryRequest struct {
	Question  string `json:"question" binding:"required,max=4096"`
	Workspace string `json:"workspace" binding:"required"`
	Mode      string `json:"mode" binding:"required,oneof=vector keyword hybrid"`
	TopK      int32  `json:"topK" binding:"omitempty,min=1,max=20"`
}

type CreateWorkspaceRequest struct {
	Name        string          `json:"name" binding:"required"`
	Description string          `json:"description"`
	Config      WorkspaceConfig `json:"config"`
	Editors     []string        `json:"editors"`
}

type UpdateWorkspaceRequest struct {
	Name        *string          `json:"name"`
	Description *string          `json:"description"`
	Config      *WorkspaceConfig `json:"config"`
}

type IngestDocumentRequest struct {
	Workspace    string `json:"workspace" binding:"required"`
	DocumentData []byte `json:"document_data" binding:"required"`
	FileName     string `json:"filename" binding:"required"`
	DocumentID   string `json:"document_id" binding:"required"`
}

type WorkspaceListItem struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Config      WorkspaceConfig `json:"config"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Editors     []string        `json:"editors"`
}
