// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: agent/resource_change_proposal.proto

package gen

import (
	"encoding/json"
	"github.com/byteBuilderX/stratum/internal/agent/domain"
	"time"
)

type UpdateResourceChangeProposalRequest struct {
	Payload json.RawMessage `json:"payload" binding:"required"`
}

type ResourceChangeProposalResponse struct {
	ID                  string                   `json:"id"`
	ConversationID      string                   `json:"conversationId,omitempty"`
	ProposerID          string                   `json:"proposerId"`
	ConfirmerID         string                   `json:"confirmerId,omitempty"`
	ResourceKind        domain.ResourceKind      `json:"resourceKind"`
	ResourceID          string                   `json:"resourceId,omitempty"`
	Operation           domain.ProposalOperation `json:"operation"`
	BaselineFingerprint string                   `json:"baselineFingerprint,omitempty"`
	BaselineProjection  json.RawMessage          `json:"baselineProjection,omitempty"`
	Payload             json.RawMessage          `json:"payload"`
	Summary             string                   `json:"summary"`
	Status              domain.ProposalStatus    `json:"status"`
	ErrorCode           string                   `json:"errorCode,omitempty"`
	ApplyResult         domain.ApplyResult       `json:"applyResult,omitempty"`
	Events              []domain.ProposalEvent   `json:"events"`
	EditCount           int32                    `json:"editCount"`
	ExpiresAt           time.Time                `json:"expiresAt"`
	CreatedAt           time.Time                `json:"createdAt"`
	UpdatedAt           time.Time                `json:"updatedAt"`
}
