// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: scheduler/scheduled_task.proto

package gen

import (
	"time"
)

type CreateScheduledTaskRequest struct {
	Name          string         `json:"name" binding:"required"`
	WorkflowID    string         `json:"workflowId" binding:"required"`
	VersionID     string         `json:"versionId" binding:"required"`
	InputTemplate map[string]any `json:"inputTemplate"`
	CronExpr      string         `json:"cronExpr" binding:"required"`
}

type UpdateScheduledTaskRequest struct {
	Name          string         `json:"name" binding:"required"`
	WorkflowID    string         `json:"workflowId" binding:"required"`
	VersionID     string         `json:"versionId" binding:"required"`
	InputTemplate map[string]any `json:"inputTemplate"`
	CronExpr      string         `json:"cronExpr" binding:"required"`
}

type SetScheduledTaskEnabledRequest struct {
	Enabled bool `json:"enabled"`
}

type ScheduledTaskResponse struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	WorkflowID       string         `json:"workflowId"`
	VersionID        string         `json:"versionId"`
	InputTemplate    map[string]any `json:"inputTemplate"`
	CronExpr         string         `json:"cronExpr"`
	Enabled          bool           `json:"enabled"`
	NextFireAt       time.Time      `json:"nextFireAt"`
	LastRunAt        *time.Time     `json:"lastRunAt,omitempty"`
	LastRunStatus    string         `json:"lastRunStatus"`
	LastErrorMessage string         `json:"lastErrorMessage,omitempty"`
	CreatedBy        string         `json:"createdBy"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	WorkflowName     string         `json:"workflowName,omitempty"`
	VersionNo        int64          `json:"versionNo,omitempty"`
	VersionName      string         `json:"versionName,omitempty"`
}

type ScheduledTaskPageResponse struct {
	Tasks    []ScheduledTaskResponse `json:"tasks"`
	Total    int32                   `json:"total"`
	Page     int32                   `json:"page"`
	PageSize int32                   `json:"pageSize"`
}
