// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: skill/skill.proto

package gen

type CreateSkillRequest struct {
	Name         string   `json:"name" binding:"required"`
	Description  string   `json:"description" binding:"required"`
	Instructions string   `json:"instructions" binding:"required"`
	Editors      []string `json:"editors"`
}

type UpdateSkillDraftRequest struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	Instructions string `json:"instructions"`
}

type SkillWorkspaceResponse struct {
	Editors []string              `json:"editors"`
	Skill   SkillProductResponse  `json:"skill"`
	Draft   SkillRevisionResponse `json:"draft"`
}

type SkillProductResponse struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Status           string `json:"status"`
	ActiveRevisionID string `json:"activeRevisionId,omitempty"`
	DraftRevisionID  string `json:"draftRevisionId,omitempty"`
	IsSystem         bool   `json:"isSystem"`
}

type SkillRevisionResponse struct {
	ID            string         `json:"id"`
	SkillID       string         `json:"skillId"`
	RevisionNo    int32          `json:"revisionNo,omitempty"`
	Status        string         `json:"status"`
	Name          string         `json:"name"`
	Description   string         `json:"description"`
	Instructions  string         `json:"instructions"`
	PublishChecks map[string]any `json:"publishChecks,omitempty"`
}

type ErrorResponse struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}
