// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: workflow/workflow.proto

package gen

import (
	"github.com/byteBuilderX/stratum/internal/workflow/domain"
)

type CreateWorkflowRequest struct {
	Name        string             `json:"name" binding:"required"`
	Description string             `json:"description"`
	Spec        domain.Spec        `json:"spec" binding:"required"`
	InputSchema domain.InputSchema `json:"input_schema" binding:"required"`
}

type UpdateWorkflowRequest struct {
	Name             string             `json:"name" binding:"required"`
	Description      string             `json:"description"`
	Spec             domain.Spec        `json:"spec" binding:"required"`
	InputSchema      domain.InputSchema `json:"input_schema" binding:"required"`
	ExpectedRevision int64              `json:"expected_revision" binding:"required"`
}

type StartWorkflowRunRequest struct {
	VersionID      string         `json:"version_id" binding:"required"`
	Task           string         `json:"task" binding:"required"`
	Fields         map[string]any `json:"fields"`
	IdempotencyKey string         `json:"idempotency_key" binding:"required"`
}

type WorkflowControlRequest struct {
	ExpectedGeneration int64  `json:"expected_generation" binding:"required"`
	Reason             string `json:"reason"`
}

type WorkflowApprovalDecisionRequest struct {
	RunID              string                  `json:"run_id" binding:"required"`
	AttemptID          string                  `json:"attempt_id" binding:"required"`
	ExpectedGeneration int64                   `json:"expected_generation" binding:"required"`
	Decision           domain.ApprovalDecision `json:"decision" binding:"required,oneof=approve reject"`
	Comment            string                  `json:"comment"`
}

type WorkflowManualResolveRequest struct {
	ExpectedGeneration int64               `json:"expected_generation" binding:"required"`
	Action             domain.ManualAction `json:"action" binding:"required"`
	OutputSummary      string              `json:"output_summary"`
}
