// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: sample.proto

package gen

import (
	"github.com/byteBuilderX/stratum/internal/agent/domain"
	"time"
)

type SampleScalars struct {
	ID        string  `json:"id"`
	Revision  int64   `json:"revision"`
	Page      int32   `json:"page"`
	Enabled   bool    `json:"enabled"`
	Score     float64 `json:"score"`
	Threshold float32 `json:"threshold"`
	Blob      []byte  `json:"blob"`
}

type SampleMappings struct {
	Name        string                    `json:"name" binding:"required,max=255"`
	CreatedAt   time.Time                 `json:"created_at"`
	Status      domain.OpProposalStatus   `json:"status"`
	Config      map[string]any            `json:"config"`
	SampleInput any                       `json:"sample_input"`
	Maybe       *bool                     `json:"maybe"`
	Detail      string                    `json:"detail,omitempty"`
	Tags        []string                  `json:"tags"`
	Headers     map[string]string         `json:"headers"`
	Steps       []SampleScalars           `json:"steps"`
	Overrides   map[string]map[string]any `json:"overrides"`
}
