// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: sample.proto

export interface SampleScalars {
  id: string;
  revision: number;
  page: number;
  enabled: boolean;
  score: number;
  threshold: number;
  blob: string;
}

export interface SampleMappings {
  name: string;
  created_at: string;
  status: string;
  config: Record<string, unknown>;
  sample_input: unknown;
  maybe?: boolean | null;
  detail?: string;
  tags: string[];
  headers: Record<string, string>;
  steps: SampleScalars[];
  overrides: Record<string, Record<string, unknown>>;
  events: unknown[];
  maybe_config?: unknown | null;
  value_map: Record<string, unknown>;
}

