package main

import (
	"fmt"
	"go/format"
	"go/token"
	"go/types"
	"strings"
)

// resolved message/struct names used for cross-message references.
var structNames = map[string]string{} // fully-qualified proto name -> Go struct name

// messageType resolves a fully-qualified proto TypeName to the generated
// Go type. google.protobuf WKTs map to plain Go types (no runtime); user
// messages resolve via structNames — same-file references live in the same
// gen package, so the resolved name is just the struct name. Unknown
// TypeName (cross-file reference) fails closed: the mapping table has no
// entry, the generator must not guess.
func messageType(typeName string) (string, error) {
	switch typeName {
	case ".google.protobuf.Timestamp":
		return "time.Time", nil
	case ".google.protobuf.Struct":
		return "map[string]any", nil
	case ".google.protobuf.Value":
		return "any", nil
	}
	if goName, ok := structNames[typeName]; ok {
		return goName, nil
	}
	return "", fmt.Errorf("message %q not in this file (cross-file references unsupported; add to structNames via import)", typeName)
}

// resolveGoType validates a @gotype value against the whitelist. The base
// type path must be a stratum/internal package, encoding/json, or time
// (RawMessage / Duration are proto-inexpressible); builtin expressions with
// no dots (e.g. map[string][]any) are allowed. Pointer/slice/map prefixes
// are stripped before the check (*domain.AuthConfig, []domain.ProposalEvent).
func resolveGoType(gt string) (string, error) {
	expr, err := types.Eval(token.NewFileSet(), nil, 0, gt)
	if err != nil {
		return "", fmt.Errorf("@gotype %q is not a valid Go type expression", gt)
	}
	_ = expr
	if !strings.Contains(gt, ".") {
		return gt, nil // builtin expression (map/slice of builtins)
	}
	// strip pointer/slice/map prefixes to reach the base type path
	base := gt
	for strings.HasPrefix(base, "*") || strings.HasPrefix(base, "[]") {
		base = base[1:]
	}
	if strings.HasPrefix(base, "map[") {
		if idx := strings.Index(base, "]"); idx >= 0 {
			base = base[idx+1:] // map[K]V -> V
		}
	}
	for _, allow := range []string{
		"github.com/byteBuilderX/stratum/internal/",
		"encoding/json.",
		"time.",
	} {
		if strings.HasPrefix(base, allow) {
			return gt, nil
		}
	}
	return "", fmt.Errorf("@gotype %q outside whitelist (only stratum/internal, encoding/json, time, or builtin expressions)", gt)
}

// collectImports returns the set of package paths referenced by field types,
// stripping pointer/slice/map prefixes before extracting the package path
// (*github.com/.../domain.X -> github.com/.../domain, map[string][]any ->
// no dot, no import; time.Time -> time).
func collectImports(msgs []*message) map[string]bool {
	imports := map[string]bool{}
	for _, m := range msgs {
		for _, f := range m.Fields {
			base := strings.TrimLeft(f.GoType, "*[]")
			if strings.HasPrefix(base, "map[") {
				if idx := strings.Index(base, "]"); idx >= 0 {
					base = base[idx+1:]
				}
			}
			if idx := strings.LastIndex(base, "."); idx >= 0 {
				imports[base[:idx]] = true
			}
		}
	}
	return imports
}

// goFile renders one .go file with a struct per message. The buffer is
// passed through go/format so import grouping and alignment always satisfy
// gofmt; a format error means a generator bug (tested, not silent).
func goFile(msgs []*message, protoPath string) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by protoc-gen-ginstruct. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// source: %s\n\n", protoPath)
	b.WriteString("package gen\n\n")
	// collect imports: strip pointer/slice/map prefixes before extracting
	// the package path (*github.com/.../domain.X -> github.com/.../domain,
	// map[string][]any -> no dot, no import; time.Time -> time).
	if imports := collectImports(msgs); len(imports) > 0 {
		b.WriteString("import (\n")
		for pkgPath := range imports {
			fmt.Fprintf(&b, "\t%q\n", pkgPath)
		}
		b.WriteString(")\n\n")
	}
	for _, m := range msgs {
		fmt.Fprintf(&b, "type %s struct {\n", m.GoName)
		for _, f := range m.Fields {
			fmt.Fprintf(&b, "\t%-24s %s `%s`\n", f.GoName, f.GoType, f.JSONTag)
		}
		b.WriteString("}\n\n")
	}
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(fmt.Sprintf("generator produced invalid Go: %v", err)) // generator bug, tests catch it
	}
	return src
}
