package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

// goFileName maps a proto path to the generated Go output path. Both
// outputs live in fixed gen/ dirs, basename-derived (one file per proto).
func goFileName(protoPath string) string {
	return "api/http/dto/gen/" + strings.TrimSuffix(filepath.Base(protoPath), ".proto") + ".go"
}

func tsFileName(protoPath string) string {
	return "web/src/services/gen/" + strings.TrimSuffix(filepath.Base(protoPath), ".proto") + ".ts"
}

// tsFile renders one .ts file: `export interface <Name> { ... }` per message.
// Field names are the proto json keys verbatim (same bytes as Go's json
// tags), so axios consumes the response JSON directly — no protojson, no
// runtime. TSType was already computed by Task 1's shared type mapping.
// @omitempty / proto3 optional fields become optional properties (`?`),
// matching the hand-written zod `.optional()` semantics across the frontend.
func tsFile(msgs []*message, protoPath string) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by protoc-gen-ginstruct. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// source: %s\n\n", protoPath)
	for _, m := range msgs {
		fmt.Fprintf(&b, "export interface %s {\n", m.GoName)
		for _, f := range m.Fields {
			opt := ""
			if f.OmitZero || f.Optional {
				opt = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", f.TSName, opt, f.TSType)
		}
		b.WriteString("}\n\n")
	}
	return []byte(b.String())
}
