grafana:
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL

alertmanager:
  enabled: true
  alertmanagerSpec:
    retention: 120h
    replicas: 1

prometheus:
  enabled: true
  prometheusSpec:
    retention: 15d
    retentionSize: 15GB
    replicas: 1
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 250m
        memory: 768Mi
      limits:
        cpu: "1"
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

kubeEtcd:
  enabled: true
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
