app:
  replicaCount: 2

config:
  secureCookies: "true"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          service: frontend
  tls:
    - secretName: stratum-ingress-tls
