app:
  replicaCount: 2

config:
  secureCookies: "false"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web,web2,websecure"
    traefik.ingress.kubernetes.io/router.tls: "false"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          service: frontend
  tls: []
